### ISSUE TITLE
Delete Image

### ISSUE THREAD

**Issue by rahmanQaiser** [codingo-me/dropzone-laravel-image-upload#3]
Hi,
I've uploading images with drop zone and ajax.
When the user upload image and submit form,  image path is sorted in database. But when user uploads images and leaves page without submitting the form, i want to delete that uploaded image. How should i do that?
OR is there any other batter practice for this implementation.

Thanks!

**Comment by ivanderbu2** [comment]
You should prevent auto processing of upload queue and add submit button to your form.
