### ISSUE TITLE
New Install returns - Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by RafaelDeJongh** [codingo-me/dropzone-laravel-image-upload#8]
Downloading and using the composer install command returns an empty "Whoops, looks like something went wrong.".

I've tried multiple times downloading different versions of Laravel, but without luck. Could you provide a full version of a working example?

**Comment by michaelsreuben** [comment]
There some missing files in the repository..
failed to open stream: No such file or directory in C:\Users\Path_to_\projects\htdocs\dropzone\bootstrap\autoload.php on line 17

**Comment by ivanderbu2** [comment]
I guess you're not properly installing project, cause that missing file on line 17 is located in vendor folder. First you need to clone this project, then go into cloned folder and issue `composer install`
This last command will install all the dependencies and add vendor folder to your project. Of course, you need to have composer installed on your dev system.

**Comment by RafaelDeJongh** [comment]
@ivanderbu2 

I am not having the same problem as @michaelsreuben, as mentioned when using the install command and using all kinds of laravel versions, it just returns an empty "Whoops, looks like something went wrong." nothing else of error codes.

In total I've tried this more than 10 times, yet all with the same result. (Cloned, Downloaded the ZIP, etc).

**Comment by RafaelDeJongh** [comment]
As a followup I've yet tried another time again and this is the Install I'm receiving:

`
D:\xampp\htdocs\AP-Images-Try\dropzone-laravel-image-upload-master>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 60 installs, 0 updates, 0 removals
  - Installing nikic/php-parser (v2.1.0) Loading from cache
  - Installing classpreloader/classpreloader (3.0.0) Loading from cache
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing psr/http-message (1.0) Loading from cache
  - Installing guzzlehttp/psr7 (1.3.0) Loading from cache
  - Installing intervention/image (2.3.7) Loading from cache
  - Installing jakub-onderka/php-console-color (0.1) Loading from cache
  - Installing symfony/polyfill-util (v1.2.0) Loading from cache
  - Installing symfony/polyfill-php56 (v1.2.0) Loading from cache
  - Installing jeremeamia/superclosure (2.2.0) Loading from cache
  - Installing vlucas/phpdotenv (v2.3.0) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.2.0) Loading from cache
  - Installing symfony/var-dumper (v3.0.7) Loading from cache
  - Installing symfony/translation (v3.0.7) Loading from cache
  - Installing symfony/routing (v3.0.7) Loading from cache
  - Installing symfony/process (v3.0.7) Loading from cache
  - Installing symfony/http-foundation (v3.0.7) Loading from cache
  - Installing symfony/event-dispatcher (v3.1.1) Loading from cache
  - Installing psr/log (1.0.0) Loading from cache
  - Installing symfony/debug (v3.0.7) Loading from cache
  - Installing symfony/http-kernel (v3.0.7) Loading from cache
  - Installing symfony/finder (v3.0.7) Loading from cache
  - Installing symfony/console (v3.0.7) Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.2) Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2) Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1) Loading from cache
  - Installing psy/psysh (v0.7.2) Loading from cache
  - Installing paragonie/random_compat (v1.4.1) Loading from cache
  - Installing nesbot/carbon (1.21.0) Loading from cache
  - Installing mtdowling/cron-expression (v1.1.0) Loading from cache
  - Installing monolog/monolog (1.19.0) Loading from cache
  - Installing league/flysystem (1.0.24) Loading from cache
  - Installing laravel/framework (v5.2.39) Loading from cache
  - Installing laravelcollective/html (v5.2.4) Loading from cache
  - Installing fzaninotto/faker (v1.6.0) Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2) Loading from cache
  - Installing mockery/mockery (0.9.5) Loading from cache
  - Installing webmozart/assert (1.0.2) Loading from cache
  - Installing phpdocumentor/reflection-common (1.0) Loading from cache
  - Installing phpdocumentor/type-resolver (0.2) Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.1.0) Loading from cache
  - Installing symfony/yaml (v3.1.1) Loading from cache
  - Installing sebastian/recursion-context (1.0.2) Loading from cache
  - Installing sebastian/exporter (1.2.2) Loading from cache
  - Installing sebastian/diff (1.4.1) Loading from cache
  - Installing sebastian/comparator (1.2.0) Loading from cache
  - Installing doctrine/instantiator (1.0.5) Loading from cache
  - Installing phpspec/prophecy (v1.6.1) Loading from cache
  - Installing phpspec/php-diff (v1.0.2) Loading from cache
  - Installing phpspec/phpspec (2.5.0) Loading from cache
  - Installing phpunit/php-token-stream (1.4.8) Loading from cache
  - Installing sebastian/version (1.0.6) Loading from cache
  - Installing sebastian/global-state (1.1.1) Loading from cache
  - Installing sebastian/environment (1.3.7) Loading from cache
  - Installing phpunit/php-text-template (1.2.1) Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8) Loading from cache
  - Installing phpunit/php-timer (1.0.8) Loading from cache
  - Installing phpunit/php-file-iterator (1.4.1) Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4) Loading from cache
  - Installing phpunit/phpunit (4.8.26) Loading from cache
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/translation suggests installing symfony/config ()
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
psy/psysh suggests installing ext-readline (Enables support for arrow-key history navigation, and showing and manipulating command history.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.4).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~5.3|~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/css-selector (Required to use some of the crawler integration testing tools (2.8.*|3.0.*).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (2.8.*|3.0.*).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (0.2.*).)
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 ÔÇô Adds Nyan formatters)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
[32mGenerating optimized class loader[39m
[32mCompiling common classes[39m

D:\xampp\htdocs\AP-Images-Try\dropzone-laravel-image-upload-master>`

And this is the error I'm receiving:

![14151700-clipboard0.png](https://ap-images.ga/up/2017/01/14151700-clipboard0.png "14151700-clipboard0.png")

So yea this has nothing to do with the vendor problem of @michaelsreuben as the install was completely successful so far as I read the above installation. But well as said a couple of times now, the actual application does in fact not function on install and first visit.

**Comment by ivanderbu2** [comment]
I guess you are new to Laravel, you need to turn debug mode ON in .env file to see exact error message, or go into laravel.log and see what it says. This looks like permission problem with new Laravel installation which is common issue, you need to set 777 permissions on bootstrap and storage folders.

**Comment by RafaelDeJongh** [comment]
@ivanderbu2 

No that wasn't it, debugging was definitly on as I get normal errors on my other installation. Permission is also properly set to every folder and sub-folder. to fully read & write. 

So yea nothing of those two I'm afraid.

**Comment by ivanderbu2** [comment]
It is a good practice to never commit environment files that is why I committed .env.example file. After you clone project you rename or copy content of example file to .env Every Laravel project on the web is using same practice. 
From log file I can see that Laravel is dropping chiper error, that means that length of APP_KEY element in .env file is not good and you should run `php artisan key:generate`

**Comment by RafaelDeJongh** [comment]
Great! Thanks for the information, this sure will help me further in my process ;)
